### PR TITLE
fix mixed content sitewide: http -> https (bug 844010)

### PR DESCRIPTION
**Pull request by cvan**
My editor strips trailing whitespace (which there was a lot of). To see the non-whitespace changes:
https://github.com/cvan/web-forward/commit/432d608?w=0

The bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=844010

### CODE REVIEW

**Comment by msujaws** [comment]
Anything that can be done to get this PR prioritized?

**Comment by retornam** [comment]
@cvan I have the right permissions on this repo so I can get this merged after you fix the merge conflicts

**Comment by cvan** [comment]
@retornam updated

**Comment by retornam** [comment]
thanks @cvan

**Pull request merged**
